services:
  # app:
  #   build:
  #     context: ../backend/zzimcong
  #     dockerfile: Dockerfile
  #   container_name: zzimcong-app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #     - redis
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/zzimcong?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  #     SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
  #     SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
  #     SPRING_REDIS_HOST: redis
  #     SPRING_REDIS_PORT: 6379

  db:
    image: mysql:8.0
    container_name: zzimcong-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: zzimcong
    volumes:
      - ../database/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ../database/init:/docker-entrypoint-initdb.d
      # - ../database/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2-alpine
    container_name: zzimcong-redis
    ports:
      - "6379:6379"
    volumes:
      - ../database/redis-data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # jenkins:
  #   build:
  #     context: ./jenkins
  #     dockerfile: Dockerfile
  #   container_name: zzimcong-jenkins
  #   privileged: true
  #   user: root
  #   ports:
  #     - "9090:9090"
  #     - "50000:50000"
  #   volumes:
  #     - ./jenkins_home:/var/jenkins_home
  #     - /var/run/docker.sock:/var/run/docker.sock
