spring:
  profiles:
    active: local
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/zzimcong?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:29092
    consumer:
      group-id: product-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka/

server:
  port: 8082

logging:
  level:
    com.zzimcong.product: DEBUG
    p6spy: INFO
    org.hibernate: WARN
    org.springframework: WARN

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: false
      logging: slf4j
      log-format: "%(executionTime)ms | %(category) | connection %(connectionId) | %(sql)"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: prometheus