global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "spring-boot-apps"
    metrics_path: "/actuator/prometheus"
    eureka_sd_configs:
      - server: http://eureka-server:8761/eureka
  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-gateway:8080"]
  - job_name: "eureka-server"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["eureka-server:8761"]
